# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 86084b3e6f0041b353b74268240ee327d9d00737326c83e04493d3dcfee85ae72fec5338bc8a471d0ad97e1ee6631dd2058b6e1619203ce21f324d700b43dea9

test:
  secret_key_base: 103e1625921a8f5a7b2140d913dae6d64a0d0f0d0355c30008a27d56c194ad717ca0abfce2da75ba2a95e371d8cb404609355d0e8c01288e3b5b329ed1c826de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
